### ISSUE TITLE
 ポートフォリオ作成 

### ISSUE THREAD

**Issue by m0216i** [react-workspace/react-portfolio-site#5]
- [x] ライフサイクルとUseEffect
- [x] レンダリングとUseState
- [x] ビジネスロジックとUseReducer
- [x] UseReducerで実装する。
- [x] ステートに応じて動的にviewを更新する
- [x] TestTableとカスタムフックス
- [x] 実践リファクタリング

https://www.techpit.jp/courses/194/curriculums/197/sections/1312/parts/5289

**Comment by Kurogoma939** [comment]
@m0216i 
複数プロジェクト同じリポジトリに入れようとしていない？

**Comment by m0216i** [comment]
@Kurogoma939 
大丈夫です！
最初、そのように作ってしまって、React_1のフォルダが残ってしまっていますが、
次回から１つのリポジトリにつき、１つというかたちで作ります！

**Comment by Kurogoma939** [comment]
@m0216i 
次の課題からで良いですが、
そのチェックボックス単位でissueとブランチを切って、
それで各々作業してコミットしてをしてほしいです！

**Comment by m0216i** [comment]
@Kurogoma939 
承知しました！！
有り難うございます！
