### ISSUE TITLE
READMEの起票について

### ISSUE THREAD

**Issue by Kurogoma939** [react-workspace/react-portfolio-site#6]
@m0216i 
１リポジトリに対し、１アプリでお願いします。
こちらのリポジトリに対し、後からみた時に「どんな意図を持った学習・アプリか」がわかるよう
READMEを設定しておきましょう。

以下の内容を設定してください。

- [x] アプリ概要
- [x] 主要機能（学習目的）
- [x] 参考サイト
- [x] 備考

### 参考
私も結構サボっちゃってるけど、このくらいできるといいと思う
https://github.com/kurogoma-flutter/mini_word_test

**Comment by m0216i** [comment]
@Kurogoma939 
石毛さん、お手隙の際に確認をお願いします！

**Comment by Kurogoma939** [comment]
@m0216i 
内容はとりあえず良いです！が、
提出をするのであれば絶対PRで提出してくださいね！
main書き換えて「みてください」だとダメだった場合面倒です。。。

**Comment by m0216i** [comment]
@Kurogoma939 
なるほど！すみません！今度気をつけます！
有難うございます！！
